## Pointer based registration
pointer:
  tooltip name: drill_tip # Rigid body that is attached to the tip of the tool
  name of points:
    - P01_04_real_pre_1 
    - P01_04_real_pre_2
    - P01_04_real_pre_3
    - P01_04_real_pre_4
    - P01_04_real_pre_5
    - P01_04_real_pre_6
    - P01_04_real_pre_7


  object name: Segmentation_Anatomical_Origin

## Pivot calibration
pivot:
  marker namespace: /atracsys/drill_marker
  marker name: marker  #AMBF drill body name
  type: AUTO
  resolution: 0.01
  number of points: 150
