## Pointer based registration
pointer:
  tooltip name: drill_empty_reference # Rigid body that is attached to the tip of the tool
  name of points:
    - F_B1
    - F_01
    - F_05
    - F_10
    - F_13
    - F_17

  object name: volume_anatomical_origin

## Pivot calibration
pivot:
  marker namespace: /atracsys/drill_marker/
  marker name: marker  #AMBF drill body name
  type: AUTO
  resolution: 0.01
  number of points: 150