## Pointer based registration
pointer:
  tooltip name: drill_tip # Rigid body that is attached to the tip of the tool
  name of points:
    - F01
    - F5
    - F10
    - F13
    - F17
    # - FCENTER

  object name: volume_anatomical_origin

## Pivot calibration
pivot:
  marker namespace: /atracsys/drill_marker/
  marker name: marker  #AMBF drill body name
  type: AUTO
  resolution: 0.01
  number of points: 150
