## Test config file for the spacenav

control objects:
- CAMERA main_camera
- VOLUME mastoidectomy_volume
- BODY drill_empty_reference
- BODY drill_tip  

# Scaling for the motion
scaling: [0.000001 , 0.000001, 0.000001, 0.0001, 0.0001, 0.0001]
# scaling: [0.01 , 0.01, 0.01, 0.000, 0.000, 0.000]

# Deadbound
deadbound:
  translation: 0.1
  rotation: 0.1

# The number of polls needed to be done 
# before the device is considered "static"
static count threshold: 100

# Scaling used for moving the rigid bodys
velocity sclaing:
  linear: 100.0
  angular: 2.0